### ISSUE TITLE
Pressing back in Nala during Permission flow seems to cause crash

### ISSUE THREAD

**Issue by davkutalek** [UseHover/SDK-Issues#18]
https://console.firebase.google.com/u/1/project/nala-interface/crashlytics/app/android:money.nala.pay/issues/5c258bcff8b88c29636bce21?time=last-seven-days&sessionId=5C59EFBC0083000135FC54BC914ADA16_DNE_3_v2

**Comment by davkutalek** [comment]
Unable to reproduce, but our back stack is messed up during the permission flow. I will try updating to the androidx appcompat packages and try to reproduce it again.

**Comment by stcastle** [comment]
Updating to androidx is a bit of a pain, so watch out.

I tried adding this to the bottom of our app-level build.gradle file, unfortunately I still see a [similar crash](https://console.firebase.google.com/u/0/project/nala-interface/crashlytics/app/android:money.nala.pay/issues/5c46edddf8b88c29631cee44) with this, so it didn't fix the problem. It's possible that this line at the bottom of my build.gradle file isn't actually doing anything though.

`configurations {
    all*.exclude group: 'com.android.support', module: 'appcompat-v7'
}`

**Comment by davkutalek** [comment]
Couldn't reproduce after updating test app to androidx, but that was on an older phone. Going to try to reproduce it again on an 8.0+ phone

**Comment by davkutalek** [comment]
Reproduced on Android 8.0+, full stacktrace:

2019-02-13 12:39:06.850 15113-15113/com.hover.tester.manual E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hover.tester.manual, PID: 15113
    android.view.InflateException: Binary XML file line #9: Binary XML file line #14: Error inflating class TextView
    Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class TextView
    Caused by: java.lang.NumberFormatException: For input string: "bold"
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:133)
        at android.content.res.TypedArray.getInt(TypedArray.java:383)
        at android.widget.TextView.readTextAppearance(TextView.java:3577)
        at android.widget.TextView.<init>(TextView.java:959)
        at android.widget.TextView.<init>(TextView.java:869)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:87)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:83)
        at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:177)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:102)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:995)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.hover.sdk.ui.TransactingFragment.onCreateView(TransactingFragment.java:82)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7165)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
2019-02-13 12:39:06.850 15113-15113/com.hover.tester.manual E/AndroidRuntime:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by davkutalek** [comment]
Due to using `textFontWeight = bold` in TextViews. Shouldn't do that, use `textStyle` instead. Fixed in `0.17.0-SNAPSHOT04+`
