### ISSUE TITLE
Transaction Session Crash

### ISSUE THREAD

**Issue by KnightWorker37** [UseHover/SDK-Issues#68]
### Problem

On the Hover transacting screen we are getting a lot of random crashes with this stack trace:

```log
java.lang.NullPointerException: 
  at com.hover.sdk.ui.if.ı (if.java)
  at com.hover.sdk.ui.ScreenBlockerService.ı (ScreenBlockerService.java)
  at com.hover.sdk.ui.ScreenBlockerService$5.run (ScreenBlockerService.java)
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6524)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:451)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:888)
```

### Environment

Most of the crashes (**80%**) are on the same model of device (**Infinix-X559C**)
**RAM (total memory)**: 1,024 MB (958 MB)
**System on Chip (SOC)**: Mediatek MT6580
**CPU**: 4x ARM Cortex-A7 (1500 Mhz)
**ABI**: armeabi-v7a, armeabi
**Device type**: Phone
**Screen size**: 720x1280
**Screen density (DPI)**: 320 (xhdpi)
**Android version**: Android 7.0 (SDK 24)
**OpenGL ES version**: 2.0
**GPU**: ARM Mali 400 (500 Mhz)

**Comment by davkutalek** [comment]
@KnightWorker37 what version of the Hover SDK are you using?

**Comment by Mangielijah** [comment]
i am using latest version of hover 1.7.3
and transaction crashes on android 12

**Comment by Mangielijah** [comment]
Any help with this issue🙏🏾🙏🏾, the SDK crashes on android 12, using a Google pixel 3a

**Comment by Mangielijah** [comment]
Here is the error its related to some permission

` java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from com.omenacle.payme (pid=16223, uid=10324) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5722)
        at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1185)
        at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:479)
        at com.hover.sdk.utils.TimerSingleton$1.onTick(TimerSingleton.java:58)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:145)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.wm.ActivityTaskManagerService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:3012)
        at com.android.server.wm.ActivityTaskManagerService.access$1100(ActivityTaskManagerService.java:297)
        at com.android.server.wm.ActivityTaskManagerService$LocalService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:5467)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13224)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:12793)`

**Comment by Mangielijah** [comment]
[https://developer.android.com/about/versions/12/behavior-changes-all#close-system-dialogs]( https://developer.android.com/about/versions/12/behavior-changes-all#close-system-dialogs)

**Comment by KnightWorker37** [comment]
@Mangielijah I think your issue is different from what am experiencing **so you should may be open another issue**. A workaround could be:

- requesting the accessibility & draw over permissions **not** using the `com.hover.sdk.permissions.PermissionActivity`
- get these permissions before you call the SDK to run the action.

@davkutalek seems SDK needs modification for changes introduced in Android 12 as discussed here: https://developer.android.com/about/versions/12/behavior-changes-all?msclkid=3ad37f25cf7411ecb536010741f51e42#close-system-dialogs

**Comment by KnightWorker37** [comment]
This issue was fixed on our app by making sure we don't crash before calling the SDK
