### ISSUE TITLE
SDK crashes when it starts executing USSD session on Android 12+

### ISSUE THREAD

**Issue by Mangielijah** [UseHover/SDK-Issues#69]
On android 12 and higher the hover SDK crashes and throws a security exception 
`java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from com.omenacle.payme (pid=16223, uid=10324) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5722)
        at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1185)
        at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:479)
        at com.hover.sdk.utils.TimerSingleton$1.onTick(TimerSingleton.java:58)
        at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:145)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.wm.ActivityTaskManagerService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:3012)
        at com.android.server.wm.ActivityTaskManagerService.access$1100(ActivityTaskManagerService.java:297)
        at com.android.server.wm.ActivityTaskManagerService$LocalService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:5467)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13224)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:12793)`
        
you can find more info about why this error occurs here [https://developer.android.com/about/versions/12/behavior-changes-all#close-system-dialogs](https://developer.android.com/about/versions/12/behavior-changes-all#close-system-dialogs)

**Comment by Mangielijah** [comment]
Any Help or Update with this error🙏🏾

**Comment by EDUCRDC** [comment]
C'est parce que je trouve que android 12+ ne laisse pas lire les sessions USSD

**Comment by EDUCRDC** [comment]
This is because I find that android 12+ does not allow USSD sessions to be read

**Comment by AmeinEskinder** [comment]
@Mangielijah have you found fix for this issue yet?

it is giving me hard times

**Comment by ProsperChihimba** [comment]
I think the issue is Intent.ACTION_CLOSE_SYSTEM_DIALOGS is being used by HoverSDK

As of Android 12 (API Level 31) this requires a permission:
https://developer.android.com/reference/android/content/Intent#ACTION_CLOSE_SYSTEM_DIALOGS

Set your project's `targetSdkVersion` to 30, doing so puts your app into a backwards compatibility mode (targeted as Android 11) when running on Android 12 devices and will most likely bypass this issue.
